
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

#basedatos.properties

basedatos.url=jdbc:mysql://localhost:3306/SistemaPracticasProfesionales
basedatos.usuario=administrador
basedatos.contrasenia=administradorfei9
